// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBus1Z_Zdc_xhr6hdlhIvimZzflG1DD01g',
    appId: '1:131042284536:web:9b17d0f8337347a177bc0d',
    messagingSenderId: '131042284536',
    projectId: 'spsole-7e486',
    authDomain: 'spsole-7e486.firebaseapp.com',
    storageBucket: 'spsole-7e486.firebasestorage.app',
    measurementId: 'G-DH0MQ50TPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8YuOtfbWcMwCQj_hcp5LP9jQGnq4MTtQ',
    appId: '1:131042284536:android:19a650af88f91ba377bc0d',
    messagingSenderId: '131042284536',
    projectId: 'spsole-7e486',
    storageBucket: 'spsole-7e486.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBus1Z_Zdc_xhr6hdlhIvimZzflG1DD01g',
    appId: '1:131042284536:web:17c36081d602174777bc0d',
    messagingSenderId: '131042284536',
    projectId: 'spsole-7e486',
    authDomain: 'spsole-7e486.firebaseapp.com',
    storageBucket: 'spsole-7e486.firebasestorage.app',
    measurementId: 'G-Q1L5ET4N2N',
  );
}
